name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install
        run: npm ci || npm install --no-audit --fund=false

      - name: Nx affected - build
        run: npm run affected:build

      - name: Nx affected - test
        run: npm run affected:test
