name: Contracts

on:
  pull_request:

jobs:
  contracts:
    name: Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare "$(node -p "require('./package.json').packageManager")" --activate
      - run: pnpm install --frozen-lockfile
      - run: pnpm nx run contracts:test
